pr_checks:
  title:
    - name: 'prefix_check'
      regex: '^(fix|feat)'
      message_if_not_matching: 'PR title must start with "fix" or "feat"' # optional
      message_if_matching: 'PR title starts with "fix" or "feat"' # optional - provide at least one of these

  description:
    - name: 'docs_check'
      regex: 'https://docs\.example\.com' # Matching anywhere in the description
      message_if_not_matching: 'PR description must contain a link to the docs'

  file_path:
    - name: 'anywhere'
      regex: '^.*' # Regex for matching file path, relative to the root of the repository
      reviewers:
        - 'maniexx' # Use GitHub usernames
