name: Pull request checks
run-name: PR checks
on:
  pull_request:
    types: [opened, synchronize, edited]
permissions:
  pull-requests: write

jobs:
  pr_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run pr checks
        uses:  franciszekzak/fyle-pr-action@v0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/pr_checks_config.yaml